homeserver:
  type: 'synapse' # only 'synapse' is supported for now, requires postgres
  db:
    hostname: localhost
    username: matrix
    password: your_password_here
    database: synapse

web:
  address: '0.0.0.0'
  port: 8184

# Series configuration data for the graphs
series:
  users:
    # Categorize your users with patters. % matches any character
    - label: Twitter
      pattern: '@_twitter%'
      color: '#008FFF'
    # Series without a pattern will match anyone not included in another pattern.
    # In this example, anyone who is not a Twitter user will be 'Other'
    - label: Other
      color: '#FFAA00'
  rooms:
    # Categorize your rooms with patters. % matches any character
    - label: Twitter
      pattern: '#_twitter%'
      color: '#008FFF'
    # Series without a pattern will match any room not included in another pattern.
    # In this example, any room that is not a Twitter room will be 'Other'
    - label: Other
      color: '#FFAA00'

# Settings for controlling how logging works
logging:
  file: logs/graphs.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5